#Production
profiles: pro
server:
  port: 8089
spring:
  datasource:
    url: jdbc:h2:mem:h2db
    username: sa
    password:
    driverClassName: org.h2.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    schema: classpath:db/schema.sql
  devtools:
    livereload:
      enabled: false
logging:
  config: classpath:log4j.xml
#Config Actuator Health, config auth false
management:
  port: 54001
  security:
    enabled: false
  health:
    mail:
      enabled: false
#从pom.xml中获取
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"
endpoints:
  health:
    sensitive: false